// w6_ReactRouter/src/App.jsx
import React from 'react'
import {Route,Link,Redirect,Switch,NavLink,withRouter} from 'react-router-dom'
import { Menu,Layout,Row,Col,Button } from 'antd';
import {
    HomeOutlined,
    LoginOutlined,
    UserOutlined,
    EyeOutlined,
  } from '@ant-design/icons';

import Home from './views/Home'
import Login from './views/Login'
import Reg from './views/Reg'
import Discover from './views/Discover'
import Mine from './views/Mine'

import 'antd/dist/antd.css'
import './App.scss';

function App(props){
    console.log('App.props',props);
    const currentPath = props.location.pathname
    const nav = [{
        path:'/home',
        text:'首页',
        name:'home',
        icon:<HomeOutlined/>
    },{
        path:'/discover',
        text:'发现',
        name:'discover',
        icon:<EyeOutlined />
    },{
        path:'/mine',
        text:'我的',
        name:'mine',
        icon:<UserOutlined/>
    },
        // {
        //     path:'/login',
        //     text:'登录',
        //     name:'login',
        //     icon:<LoginOutlined/>
        // },{
        //     path:'/reg',
        //     text:'注册',
        //     name:'reg',
        //     icon:<UserOutlined/>
        // }
    ];
    const changeMenu = function({key}){
        props.history.push(key);
    }
    const goto = function(path,e){
        console.log('path',path,e);
        props.history.push(path)
    }
    return <Layout>
        <Layout.Header style={{padding:0}}>
            {/* <Link to="/home">首页</Link>
            <Link to="/login">登录</Link>
            <Link to="/reg">注册</Link> */}
            {/* {
                nav.map(item=><NavLink 
                    key={item.name} 
                    to={item.path}
                    // activeStyle={{color:'#f00',fontWeight:'bold'}}
                    activeClassName='active'
                >{item.text}</NavLink>)
            } */}
            <Row>
                <Col span={16}>
                    <Menu mode="horizontal" theme="dark" onClick={changeMenu} defaultSelectedKeys={[currentPath]}>
                        {
                            nav.map(item=><Menu.Item 
                                key={item.path} 
                                icon={item.icon}
                            >{item.text}</Menu.Item>)
                        }
                    </Menu>
                </Col>
                <Col span={8} style={{textAlign:'right'}}>
                    <Button type="link" onClick={goto.bind(null,'/login')}>登录</Button>
                    <Button type="link" onClick={goto.bind(null,'/reg')}>注册</Button>
                </Col>
            </Row>

        </Layout.Header>
        <Layout.Content style={{padding:20}}>
            <Switch>
                {/* <Route path="/" component={Home} exact/> */}
                <Route path="/home" component={Home}/>
                <Route path="/login" component={Login}/>
                <Route path="/reg" component={Reg}/>
                <Route path="/discover" component={Discover}/>
                <Route path="/mine" component={Mine}/>
            
                <Route path="/notfound" render={()=><div>404</div>}/>
                <Redirect from="/" to="/home" exact />
                {/* 404 */}
                {/* <Redirect from="*" to="/notfound" /> */}
                <Redirect to="/notfound" />
            </Switch>
        </Layout.Content>
    </Layout>
}

// withRouter高阶组件
App = withRouter(App)
export default App;

// w3_VueRouter/myapp/src/App.vue
<template>
  <div id="app">
    <!-- <nav>
      <router-link to="/home" tag="span" active-class="active">首页</router-link>
      <router-link to="/reg" active-class="active" replace>注册</router-link>
      <router-link to="/login" active-class="active" event="mouseover">登录</router-link>
    </nav>-->
    <!-- <button @click="$router.back()">上一页</button>
    <button @click="$router.forward()">下一页</button>
    <nav>
      <ul>
        <li v-for="item in nav" :key="item.name" @click="goto(item)" :class="{active:item.path===current}">{{item.text}}</li>
      </ul>
    </nav>
    <h4>router-view显示路由内容</h4>-->
    <el-row style="height:61px;overflow:hidden;background-color:#545c64">
      <el-col :span="18">
        <el-menu
          mode="horizontal"
          background-color="#545c64"
          text-color="#fff"
          active-text-color="#ffd04b"
          :default-active="current"
          router
        >
          <el-menu-item :index="item.path" v-for="item in nav" :key="item.name">
            <i :class="item.icon"></i>
            {{item.text}}
          </el-menu-item>
        </el-menu>
      </el-col>
      <el-col :span="6" style="border-bottom:solid 1px #e6e6e6;height:61px;overflow:hidden;text-align:right;line-height:61px;padding-right:20px;">
        <el-button type="text" @click="goto('/reg')">注册</el-button>
        <el-button type="text" @click="goto('/login')">登录</el-button>
      </el-col>
    </el-row>

    <router-view />
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      nav: [
        {
          name: "home",
          path: "/home",
          text: "首页",
          icon: "el-icon-s-home"
        },
        {
          name: "discover",
          path: "/discover",
          text: "发现",
          icon: "el-icon-view"
        },
        {
          name: "cart",
          path: "/cart",
          text: "购物车",
          icon: "el-icon-shopping-cart-2"
        }
        // {
        //   name: "login",
        //   path: "/login",
        //   text: "登录",

        // },
        // {
        //   name: "reg",
        //   path: "/reg",
        //   text: "注册"
        // }
      ],
      current: "/home"
    };
  },
  // 监听数据：监听实例的属性
  watch: {
    // 监听路由变化，实现高亮效果
    "$route.path": function(newVal, oldVal) {
      console.log(newVal, oldVal);
      this.current = newVal;
    }
  },
  methods: {
    goto(path) {
      // 编程式导航
      // this.$router.push(item.path);
      this.$router.replace(path);
    }
  },
  components: {},
  created() {
    let { path } = this.$route;
    this.current = path;
  }
};
</script>

<style lang="scss">
body{
  margin:0;
}
.price{
  span::before,del::before{
    content:'￥'
  }
  del{color:#999}
  span{color:#f00}
}
@for $i from 1 to 6{
  .m-#{$i}{
    margin:$i*0.3em;
  }
  .p-#{$i}{
    padding:$i*0.3em;
  }
}

nav a {
  margin: 0 10px;
}
.active {
  color: #f00;
  font-weight: bold;
}
</style>
