// w6_React/src/components/TodoList/index.js
import React,{Component} from 'react'

// 引入样式
import './todolist.scss';
import 'bootstrap/dist/css/bootstrap.css';

import TodoForm from './TodoForm'
import TodoContent from './TodoContent'

import MyContext from './context'


class TodoList extends Component{
    constructor(props){
        super(props);
        this.state = {
           datalist: [{
               id: 1,
               todo: '定个小目标睡一整天',
               complete: true
           }, {
               id: 2,
               todo: '赚他一个亿',
               complete: false
           }, {
               id: 3,
               todo: '迎娶白富美，达到人生巅峰',
               complete: false
           }, {
               id: 4,
               todo: '出人CEO，达到疯癫状态',
               complete: false
           }],
       }
       // 推荐在初始化时改变this指向
    //    this.addItem = this.addItem.bind(this);
    //    this.removeItem = this.removeItem.bind(this);
    //    this.completeItem = this.completeItem.bind(this);
    }
    addItem = (todo)=>{
        const {datalist} = this.state;
        const newData = {
            id:parseInt(Math.random()*10000),
            todo,
            complete:false,
            addtime:Date.now()
        }
        this.setState({
           datalist:[newData,...datalist]
        })
    }
    removeItem = (id)=>{
       let {datalist} = this.state;
       datalist = datalist.filter(item=>item.id!=id);
       this.setState({
           datalist
       })
    }
    completeItem = (id)=>{
       let {datalist} = this.state;
       datalist = datalist.map(item=>{
           if(item.id == id){
               item.complete = true
           }
           return item;
       })
       this.setState({
           datalist
       })
    }
    render(){
        const {datalist} = this.state;
        const contextData = {
            remove:this.removeItem,
            complete:this.completeItem
       };
       return(
           <div className="container">
               {/*利用Provider的value属性共享数据*/}
               <MyContext.Provider value={contextData}>
                   <TodoContent datalist={datalist} />
                   <TodoForm addItem={this.addItem}/>
               </MyContext.Provider>
           </div>
       )
    }
}

export default TodoList;

// w3_VueCLI/myapp/src/components/Todolist/index.vue
<template>
  <div class="todolist container">
    <TodoAdd v-on:add="addItem"></TodoAdd>
    <TodoContent :datalist="datalist" v-on:selectall="selectAll"></TodoContent>
    <TodoStatus :datalist="datalist"></TodoStatus>
  </div>
</template>
<script>
import TodoAdd from "./TodoAdd.vue";
import TodoContent from "./TodoContent.vue";
import TodoStatus from "./TodoStatus.vue";

import 'bootstrap/dist/css/bootstrap.css';

import Bus from './Bus';

export default {
  data() {
    return {
      datalist: [
        {
          id: 1,
          event: "定个小目标睡Ta一整天",
          complete: true,
          checked:false,
        },
        {
          id: 2,
          event: "赚他一个亿",
          complete: false,
          checked:false,
        },
        {
          id: 3,
          event: "迎娶白富美，达到人生巅峰",
          complete: false,
          checked:true,
        },
        {
          id: 4,
          event: "出人CEO，达到疯癫状态",
          complete: false,
          checked:false,
        }
      ],
      maxId: 4
    };
  },
  components: {
    TodoAdd,
    TodoContent,
    TodoStatus
  },
  methods: {
    // 添加
    addItem(data) {
      let newEvent = {
        id: ++this.maxId,
        event: data,
        complete: false
      };
      this.datalist.push(newEvent);
    },
    // 删除
    removeItem(id) {
      this.datalist = this.datalist.filter(item => item.id != id);
    },

    // 修改
    completeItem(id) {
      this.datalist.forEach(item => {
        if (item.id == id) {
          item.complete = true;
        }
      });
    },
    selectItem(id){
      this.datalist = this.datalist.map(item=>{
        if(item.id == id){
          item.checked = !item.checked;
        }
        return item;
      })
    },
    selectAll(checked){
      this.datalist = this.datalist.map(item=>{
        item.checked = checked;
        return item;
      })
    }
  },
  created(){
    Bus.$on('complete',this.completeItem)
    Bus.$on('remove',this.removeItem)
    Bus.$on('select',this.selectItem)
  },
};
</script>
<style>
ul {
  list-style: none;
}
</style>
