// w6_React/src/components/TodoList/TodoContent.js
import React from 'react'

import TodoItem from './TodoItem'

function TodoConent({datalist}){
    const completeList = datalist.filter(item=>item.complete);
    return (
        <>
            <table className="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>代办事项</th>
                        <th>是否完成</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {
                        datalist.map((item,idx)=><TodoItem key={item.id} item={item} idx={idx}></TodoItem>)
                    }
                    
                </tbody>
            </table>
            <div className="p-2 mb-3">代办事项：{datalist.length}, 完成：{completeList.length}，未完成：{datalist.length-completeList.length}</div>
       </>
    )
}

export default TodoConent

// w3_VueCLI/myapp/src/components/Todolist/TodoContent.vue
<template>
    <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">代办事项</th>
                    <th scope="col">是否完成</th>
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                <!-- <tr is="TodoItem" v-for="(item,idx) in datalist" :key="item.id" :item="item" :idx="idx"></tr> -->
                <TodoItem v-for="(item,idx) in datalist" :key="item.id" :item="item" :idx="idx" />
            </tbody>
        </table>
</template>
<script>
import TodoItem from './TodoItem.vue';
export default {
    name:'TodoContent',
    props: ['datalist'],
        template: '#todoContent',
        components: {
            TodoItem
        }
}
</script>
